### ISSUE TITLE
Als developer wil ik een fallback locatie API

### ISSUE THREAD

**Issue by erwin-iconi** [erwin-iconi/lobstr#150]

**Comment by erwin-iconi** [comment]
https://developers.google.com/maps/documentation/geolocation/intro

**Comment by Sl4rtyb4rtf4st** [comment]
Als je naar deze url gaat :
https://www.googleapis.com/geolocation/v1/geolocate?key= en dan de api places key
Dan kijg je als resultaat "Not Found"...

**Comment by erwin-iconi** [comment]
https://ipstack.com/quickstart
http://api.ipstack.com/82.73.252.93?access_key=6dc6e027a6b8757098b8e7c03728c238
