### ISSUE TITLE
Detailpage comments via AJAX

### ISSUE THREAD

**Issue by erwin-iconi** [erwin-iconi/lobstr#170]

**Comment by Sl4rtyb4rtf4st** [comment]
Om via axios data uit de database te krijgen is er een route nodig (in web.php) en een controller functie (in de comments controller ?) die daatwerkelijk de data uit de database haalt met een place_id/placeid.

**Comment by Sl4rtyb4rtf4st** [comment]
axios call: 
    axios.post('/placeDetails/store', formData)
        .then(
            // some code
        ).catch();
