### ISSUE TITLE
Toevoegen van de sterren aan de rating vanuit google

### ISSUE THREAD

**Issue by Sl4rtyb4rtf4st** [erwin-iconi/lobstr#199]

**Comment by Sl4rtyb4rtf4st** [comment]
Uiteindelijk grotendeels zelf gecodeert met een beetje hulp van een codepen voorbeeld; aanpassing van het voorbeeld:
https://codepen.io/tutsplus/pen/ayKZNL?editors=1010

**Comment by erwin-iconi** [comment]
in edge zie ik helemaal geen rating. In mijn firefox zie ik vierkantjes ipv sterretjes. @Sl4rtyb4rtf4st

**Comment by erwin-iconi** [comment]
@ Fout bij brontoewijzing: request failed with status 404
Bron-URL: http://localhost:8000/js/jquery.barrating.min.js
Brontoewijzings-URL: jquery.barrating.min.js.ma

**Comment by erwin-iconi** [comment]
@ Fout bij brontoewijzing: request failed with status 404
Bron-URL: http://localhost:8000/js/jquery.barrating.min.js
Brontoewijzings-URL: jquery.barrating.min.js.ma

**Comment by erwin-iconi** [comment]
@ Fout bij brontoewijzing: request failed with status 404
Bron-URL: http://localhost:8000/js/jquery.barrating.min.js
Brontoewijzings-URL: jquery.barrating.min.js.ma

**Comment by erwin-iconi** [comment]
@Sl4rtyb4rtf4st Fout bij brontoewijzing: request failed with status 404
Bron-URL: http://localhost:8000/js/jquery.barrating.min.js
Brontoewijzings-URL: jquery.barrating.min.js.ma
